INSERT INTO location (id, name, address) VALUES (1, 'ATL Airport','Atlanta airport location');
INSERT INTO location (id, name, address) VALUES (2, 'MIA Airport','Miami airport location');
INSERT INTO location (id, name, address) VALUES (3, 'LAX Airport','Los Angeles airport location');
INSERT INTO location (id, name, address) VALUES (4, 'PHX Airport','Phoenix airport location');
INSERT INTO location (id, name, address) VALUES (5, 'ORD Airport','Chicago airport location');
INSERT INTO dog (id, name, breed, origin) VALUES (1, 'Fluffy', 'Pomeranian', 'Mountain View, CA');
INSERT INTO dog (id, name, breed, origin) VALUES (2, 'Spot', 'Pit Bull', 'Austin, TX');
INSERT INTO dog (id, name, breed, origin) VALUES (3, 'Ginger', 'Cocker Spaniel', 'Kansas City, KS');
INSERT INTO dog (id, name, breed, origin) VALUES (4, 'Lady', 'Direwolf', 'The North');
INSERT INTO dog (id, name, breed, origin) VALUES (5, 'Sasha', 'Husky', 'Buffalo, NY');